// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm1qNaaV22nlVPj0qV4TTJpNZExzob4rA',
    appId: '1:540089355625:web:5163bda8622b4e20a4c1f8',
    messagingSenderId: '540089355625',
    projectId: 'vimquiz',
    authDomain: 'vimquiz.firebaseapp.com',
    storageBucket: 'vimquiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxNy7sVqQauU89QtqX6s0vLYmcFN2S64k',
    appId: '1:540089355625:android:860b214c05b8eed1a4c1f8',
    messagingSenderId: '540089355625',
    projectId: 'vimquiz',
    storageBucket: 'vimquiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlGC7fSr4UkYT3WIlFzvjoRhEAQI3G--w',
    appId: '1:540089355625:ios:9199dfdf812c0c41a4c1f8',
    messagingSenderId: '540089355625',
    projectId: 'vimquiz',
    storageBucket: 'vimquiz.appspot.com',
    iosClientId: '540089355625-re0toilbji2veneek14s5d875hankqi8.apps.googleusercontent.com',
    iosBundleId: 'com.example.vimquiz',
  );
}
